version: "3.7"

services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/garfield
    volumes:
      - .:/code
  db:
    image: postgres:11.4
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_DB=garfield
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
